#!/usr/bin/env bash


# Mon Oct 31 10:45:22 GMT 2011
# CASSANDRA
CASSANDRA_VERSION=0.8.5
CASSANDRA_CORE=/opt/cassandra-dev
CASSANDRA_HOME=$CASSANDRA_CORE/apache-cassandra-${CASSANDRA_VERSION}
CASSANDRA_BIN=$CASSANDRA_HOME/bin/cassandra
CASSANDRA_CONF=$CASSANDRA_CORE/cluster_config
CASSANDRA_INCLUDE=$CASSANDRA_CONF/cassandra.in.sh

# CASSANDRA.YAML
CASSANDRA_YAML=$CASSANDRA_CORE/cluster_config/cassandra.yaml
CASSANDRA_YAML_FILE=-Dcassandra.config=file:${CASSANDRA_YAML}
CASSANDRA_NODETOOL=$CASSANDRA_HOME/bin/nodetool
# LOCK FILES - IMPORTANT FOR SHUTDOWN

CASSANDRA_LOG=$CASSANDRA_CORE/log/cassandra.log
CASSANDRA_PID=$CASSANDRA_CORE/run/cassandra.pid
CASSANDRA_LOCK=$CASSANDRA_CORE/lock/subsys/cassandra
PROGRAM="cassandra"


# JDK AND ANT
JAVA_VERSION=1.6.0_27
ANT_VERSION=1.8.2
JAVA_HOME=/opt/jdk${JAVA_VERSION}
CLASSPATH=${JAVA_HOME}:${CASSANDRA_HOME}/lib
ANT_HOME=/opt/${JAVA_HOME}/apache-ant-${ANT_VERSION}

# PYTHON
PYTHON_VERSION=2.7.2
PYTHONHOME=/opt/python-${PYTHON_VERSION}

# MAVEN
M2_VERSION=3.0.3
M2_HOME=/${JAVA_HOME}/apache-maven-${M2_VERSION}

# ENV
COREPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
PATH=${PYTHONHOME}/bin:${JAVA_HOME}/bin:${M2_HOME}/bin:${ANT_HOME}/bin:${COREPATH}
